name: Test

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Prepare SSH key"
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' )}}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_algorillas
          chmod 600 ~/.ssh/id_algorillas
      - name: Production
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: bash .github/workflows/production.sh
        env:
          APP: ${{ secrets.APP }}
          DB: ${{ secrets.DB }}
